// Tüm mini oyunları kaydeder.
import './sports.js';
import './mind.js';
import './tech.js';
import './health.js';
import './trade.js';
import './life.js';
import './extra.js';
import './football.js';
import './arcade.js';
import './market.js';
import './jobs.js';
import './fun.js';
import './baby.js';
import './themes.js';
import './pack_baby.js';
import './pack_kid.js';
import './pack_jobs.js';
import './pack_teen.js';
import './pack_adult.js';
export { playMinigame, allGames, getGame, autoMods, MODIFIERS, gamesFor, pickFresh } from './engine.js';
